// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaWWnFqxtitDVTDzoq9Q9ZbBNhMukIzuI',
    appId: '1:566171578728:web:31f23ecf73536c940ce6dd',
    messagingSenderId: '566171578728',
    projectId: 'majmaa-app-dev',
    authDomain: 'majmaa-app-dev.firebaseapp.com',
    storageBucket: 'majmaa-app-dev.firebasestorage.app',
    measurementId: 'G-45G18TG6RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkr28-VgqF2-hwRvNPT75k5o62vyLFhC4',
    appId: '1:566171578728:android:701df2d64ae9beb90ce6dd',
    messagingSenderId: '566171578728',
    projectId: 'majmaa-app-dev',
    storageBucket: 'majmaa-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP6mhVqempl_haQ2H1vDZwnL5KJOkhhe8',
    appId: '1:566171578728:ios:88ffff7a3780cb490ce6dd',
    messagingSenderId: '566171578728',
    projectId: 'majmaa-app-dev',
    storageBucket: 'majmaa-app-dev.firebasestorage.app',
    iosBundleId: 'com.sherifshouaib.majmaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP6mhVqempl_haQ2H1vDZwnL5KJOkhhe8',
    appId: '1:566171578728:ios:23f87d2c1da93d3d0ce6dd',
    messagingSenderId: '566171578728',
    projectId: 'majmaa-app-dev',
    storageBucket: 'majmaa-app-dev.firebasestorage.app',
    iosBundleId: 'com.example.majmaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaWWnFqxtitDVTDzoq9Q9ZbBNhMukIzuI',
    appId: '1:566171578728:web:b9cfbc5431c151600ce6dd',
    messagingSenderId: '566171578728',
    projectId: 'majmaa-app-dev',
    authDomain: 'majmaa-app-dev.firebaseapp.com',
    storageBucket: 'majmaa-app-dev.firebasestorage.app',
    measurementId: 'G-5LK88CQGKC',
  );
}
